# Ruby のベースイメージ
FROM ruby:3.2

# 環境変数
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# 必要パッケージ
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    postgresql-client \
    curl

# Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs

# アプリケーションディレクトリ
WORKDIR /myapp

# Bundler
RUN gem install bundler

# Gemfile をコピーして bundle install
COPY Gemfile Gemfile.lock /myapp/
RUN bundle install

# アプリ全体をコピー
COPY . /myapp
