# Ruby のベースイメージ
FROM ruby:3.2

# 環境変数
ENV LANG C.UTF-8
ENV TZ Asia/Tokyo

# 必要パッケージを一度にインストール
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    postgresql-client \
    nodejs \
    npm \
    curl \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Yarn のインストール
RUN npm install -g yarn

# アプリケーションディレクトリ
WORKDIR /myapp

# Bundler のインストール
RUN gem install bundler

# Gemfile をコピーして bundle install
COPY Gemfile Gemfile.lock ./
RUN bundle install

# package.json と yarn.lock をコピー
COPY package.json yarn.lock ./

# yarn install を実行
RUN yarn install

# アプリ全体をコピー
COPY . /myapp

CMD ["bash"]
